services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: bitbalance-api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: bitbalance-client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    depends_on:
      - backend
