services:
  backend:
    build:
      context: ./backend
    container_name: bitbalance-api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=BitBalanceDb;User Id=sa;Password=${DB_PASSWORD};encrypt=false;
      # - JWT__Secret=${JWT_SECRET}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./logs:/logs

  frontend:
    build:
      context: ./frontend
    container_name: bitbalance-client
    ports:
      - "3000:80"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080
      - VITE_API_URL=http://backend:8080
    depends_on:
      - backend

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-db
    environment:
      - SA_PASSWORD=${DB_PASSWORD}
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - ${DB_STORAGE_MODE}_data:/var/opt/mssql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          '/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P ${DB_PASSWORD} -Q "SELECT 1" -b -N -C || exit 1',
        ]
      interval: 10s
      timeout: 5s
      retries: 60
      start_period: 240s
    deploy:
      resources:
        limits:
          memory: 2g

volumes:
  bind_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/sqlserver
  volume_data:
