
name: CD to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    name: Deploy Frontend to Vercel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        working-directory: src/BitBalance.Client

      - name: Deploy to Vercel (Frontend)
        run: npx vercel --token=${{ secrets.VERCEL_TOKEN }} --prod --confirm --cwd src/BitBalance.Client

  deploy-backend:
    name: Deploy Backend to Vercel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Publish API
        run: dotnet publish ./src/BitBalance.API/BitBalance.API.csproj -c Release -o ./publish

      - name: Deploy to Vercel (API)
        run: npx vercel --token=${{ secrets.VERCEL_TOKEN }} --prod --confirm --cwd publish
