
name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test-backend:
    name: .NET Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./src/BitBalance.sln

      - name: Build
        run: dotnet build ./src/BitBalance.sln --no-restore --configuration Release

      - name: Run Tests
        run: dotnet test ./tests/BitBalance.Domain.Tests/ --no-build --verbosity normal

  lint-frontend:
    name: Frontend Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/BitBalance.Client

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npx eslint src --ext .ts,.tsx
